version: '3.9'

services:
  db:
    image: postgres:15
    container_name: nihongo-postgres
    environment:
      POSTGRES_DB: nihongo_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nihongo-network

  app:
    build: .
    container_name: nihongo-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - nihongo-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nihongo_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres-data:

networks:
  nihongo-network:
